from typing import Protocol, Sequence
from inventory.domain.entities import Product

class ProductRepository(Protocol):
    def list(self, search: str | None = None) -> Sequence[Product]: ...
    def get(self, pid: int) -> Product | None: ...
    def create(self, p: Product) -> Product: ...
    def update(self, p: Product) -> Product | None: ...
    def delete(self, pid: int) -> bool: ...
