from typing import Protocol, ContextManager
from inventory.domain.ports.product_repo import ProductRepository

class UnitOfWork(Protocol, ContextManager["UnitOfWork"]):
    @property
    def products(self) -> ProductRepository: ...
    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
